name: juliocastrodev.com CI/CD config
on: push

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install and Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 10.x.x

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm cv-to-pdf && pnpm build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=website
